name: Deploy S3 stack
on:
  workflow_dispatch:
    inputs:
      stack_name:
        description: 'CloudFormation stack name'
        required: true
        default: 'my-s3-stack'
      region:
        description: 'AWS region'
        required: false
        default: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC role or static keys)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Deploy CloudFormation stack
        env:
          STACK_NAME: ${{ github.event.inputs.stack_name }}
        run: |
          echo "Deploying stack: $STACK_NAME (region: ${{ github.event.inputs.region }})"
          aws cloudformation deploy \
            --stack-name "$STACK_NAME" \
            --template-file s3-bucket-template.yaml \
            --region "${{ github.event.inputs.region }}" \
            --capabilities CAPABILITY_NAMED_IAM